{% set version = "0.4.6" %}

package:
  name: logical-unification
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/logical-unification/logical-unification-{{ version }}.tar.gz
  sha256: 908435123f8a106fa4dcf9bf1b75c7beb309fa2bbecf277868af8f1c212650a0
  patches:

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - toolz
    - multipledispatch

test:
  imports:
    - unification

about:
  home: https://github.com/pythological/unification
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Logical unification in Python.
  description: |
    Straightforward Unification, extensible via dispatch. This project has been forked from
    https://github.com/mrocklin/unification/.
  dev_url: https://github.com/pythological/unification
  doc_url: https://github.com/pythological/unification/

extra:
  recipe-maintainers:
    - brandonwillard
