{% set version = "0.4.7" %}
{% set name = "logical-unification" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pythological/unification/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 82fd074925ed0ba7674228a4c9a07611ab90e55ba1e266a9d24811ab5656618d

build:
  skip: true  # [py<39]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=80.0.0
    - setuptools-scm
  run:
    - python
    - toolz
    - multipledispatch

test:
  source_files:
    - tests
  imports:
    - unification
    - unification.core
    - unification.match
    - unification.more
    - unification.utils
    - unification.variable
  requires:
    - pip
    - pytest
    - pytest-benchmark
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests

about:
  home: https://github.com/pythological/unification
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Logical unification in Python.
  description: |
    Straightforward Unification, extensible via dispatch. This project has been forked from
    https://github.com/mrocklin/unification.
  dev_url: https://github.com/pythological/unification
  doc_url: https://github.com/pythological/unification

extra:
  recipe-maintainers:
    - brandonwillard
