{% set version = "0.4.7" %}

package:
  name: logical-unification
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/logical-unification/logical_unification-0.4.7.tar.gz
  sha256: 3d73b263a870827b3f52d89c94f3336afd7fcaecf1e0c67fa18e73025399775c
  patches:

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools >=80.0.0
    - setuptools-scm
  run:
    - python
    - toolz
    - multipledispatch

test:
  imports:
    - unification
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pythological/unification
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Logical unification in Python.
  description: |
    Straightforward Unification, extensible via dispatch. This project has been forked from
    https://github.com/mrocklin/unification/.
  dev_url: https://github.com/pythological/unification
  doc_url: https://github.com/pythological/unification/

extra:
  recipe-maintainers:
    - brandonwillard
